import '../styles/main.css';
import Router from './router';
import Navigation from './views/components/Navigation';
import AuthService from './services/auth-service';
import NotificationService from './services/notification-service';
import SkipToContent from './views/components/SkipToContent'; // Add this import

class App {
  constructor() {
    this.router = new Router();
    this.navigation = new Navigation();
    this.init();
  }

  async init() {
    // Initialize SkipToContent first, before any other components
    SkipToContent.init();
    
    // Register service worker
    if ('serviceWorker' in navigator) {
      try {
        let swPath;
        
        // Cek apakah dalam mode production atau development
        if (process.env.NODE_ENV === 'production') {
          swPath = '/service-worker.js'; // Generated by Workbox
        } else {
          swPath = '/sw-dev.js'; // Simple dev service worker
        }
        
        const registration = await navigator.serviceWorker.register(swPath);
        console.log('Service Worker registered:', registration);
        
        // Initialize push notifications
        if (AuthService.isAuthenticated()) {
          await NotificationService.init(registration);
        }
      } catch (error) {
        console.error('Service Worker registration failed:', error);
      }
    }

    // Initialize navigation
    this.navigation.render();

    // Initialize router
    this.router.init();

    // Listen for auth state changes
    window.addEventListener('auth-changed', () => {
      this.navigation.render();
    });
    
    // Ensure the main content area has the correct ID and is focusable
    const mainContent = document.getElementById('main-content');
    if (mainContent && !mainContent.hasAttribute('tabindex')) {
      mainContent.setAttribute('tabindex', '-1');
    }
  }
}

// Initialize app when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
  // Add skip link if it doesn't exist yet
  if (!document.querySelector('.skip-to-content')) {
    const skipLink = document.createElement('a');
    skipLink.className = 'skip-to-content';
    skipLink.href = '#main-content';
    skipLink.textContent = 'Skip to content';
    document.body.insertBefore(skipLink, document.body.firstChild);
  }
  
  new App();
});